# Generated by Django 5.0.7 on 2024-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_open_ended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='Quiz', max_length=255),
        ),
    ]
