# Generated by Django 5.0.7 on 2024-07-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QUIZ', '0004_question_answers_alter_question_is_open_ended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_open_ended',
        ),
    ]
